#!/bin/bash

docker kill sti_project
docker rm sti_project

docker run -ti -v //C/Users/Yannis/docker/sti:/usr/share/nginx/ -d -p 18080:80 --name sti_project --hostname sti arubinst/sti:project2018

docker exec -u root sti_project service nginx start
docker exec -u root sti_project service php5-fpm start
#docker exec -it -u root sti_project /bin/bash
